--- #YAML:1.0
name:                Apache-iTunes
version:             0.10
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Apache::Constants:             0
    Apache::FakeRequest:           0
    Apache::Util:                  0
    Mac::iTunes:                   0
    Test::More:                    0
    Text::Template:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
