# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-iTunes
version:      0.07
version_from: 
installdirs:  site
requires:
    Apache::Constants:             0
    Apache::FakeRequest:           0
    Apache::Util:                  0
    Mac::iTunes:                   0
    Test::More:                    0
    Text::Template:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
