--- #YAML:1.0
name:                Apache-iTunes
version:             0.11
abstract:            control iTunes from mod_perl
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Apache::Constants:             0
    Apache::FakeRequest:           0
    Apache::Util:                  0
    Mac::iTunes:                   0
    Test::Manifest:                1.14
    Test::More:                    0
    Text::Template:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
